name: 编译天气

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 准备开始
      uses: actions/checkout@v3
      
    - name: 设置JAVA环境
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: 建立工作目录
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: 克隆源码
      working-directory: /workdir
      run: |
        git clone https://github.com/wangshe/weather -b main weather
        ln -sf /workdir/weather $GITHUB_WORKSPACE/weather
        cd weather
        wget https://gist.github.com/wangshe/ef25a5309766a5d9c3da7bdb1a7553e1/raw/weather.patch
        git apply weather.patch

    - name: 开始编译
      run: |
        cd weather
        chmod +x gradlew
        ./gradlew assembleBasic

    - name: 上传apk
      uses: actions/upload-artifact@main
      with:
        name: weather
        path: weather/app/build/outputs/apk
